name: FTP Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: FTP deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/index.html/
        exclude: |     
          **/.git*
          **/.git*/**
          audio/*
          README.md